### ISSUE TITLE
Error installing 1.2.0 in Espocrm 8.0.2

### ISSUE THREAD

**Issue by ccolussi** [dubas-pro/ext-light-theme#13] opened 2023-09-19 12:59 UTC
Log file:

[2023-09-19 12:56:39] ERROR: Database rebuild failure, details: There is a same module in both `custom` and `internal` directories. Should be only in one location..  
[2023-09-19 12:56:40] ERROR: (500) Error occurred while EspoCRM rebuild. Please see the log for more detail.; POST /Extension/action/install; line: 282, file: /var/www/xyz_com_br/espocrm/application/Espo/Core/Upgrades/Actions/Base.php

**Comment by emillod** [comment] 2023-09-20 06:56
Hello
thank you for reaching out. We'll check this on our side.

**Comment by emillod** [comment] 2024-04-17 17:13
We couldn't reproduce your issue. There is new version of theme, please check it :) 
I'm resolving this issue for now.

**Closed as completed by emillod** 2024-04-17 17:13 UTC
